UPDATE KRCR_PARM_T
SET VAL = '01-10-2024', VER_NBR = VER_NBR + 1
WHERE NMSPC_CD = 'KFS-GL'
  AND CMPNT_CD = 'Batch'
  AND PARM_NM = 'STIPEND_PAYMENT_EXTRACT_JOB_START_DATE';

UPDATE KRCR_PARM_T
SET VAL = '15-11-2024', VER_NBR = VER_NBR + 1
WHERE NMSPC_CD = 'KFS-GL'
  AND CMPNT_CD = 'Batch'
  AND PARM_NM = 'STIPEND_PAYMENT_EXTRACT_JOB_END_DATE';
